server:
  port: 9888

spring:
  application:
    name: USER-SERVICE
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:user_service
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: never
      continue-on-error: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/